
spring:

  application:
    name: transaction-service

  datasource:
    password: userpass
    username: root

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


## MAKE GROUPED EVENT-HANDLERS UPDATE THE MAIN TABLE WITH A SINGLE THREAD
axon:
  eventhandling:
    processors:
      transaction-group:
        mode: subscribing